from graphics import *
class Board:
    # class constructor
    def __init__(self):
        self.print()

    # print
    def print(self):
        self.printouter()
        self.printinner()
        self.printbottom()
        self.printright()
        self.printtop()
        self.printleft()

    # print outer part
    def printouter(self):
        win = GraphWin()
        win.setBackground('paleturquoise')
        outlowDiag = Point(0, 0)
        outhighDiag = Point(200, 200)
        outerRect = Rectangle(outlowDiag, outhighDiag)
        
### draw lower diagonal point
##inlowDiag = Point(18, 18)
### draw upper diagonal point
##inhighDiag = Point(182, 182)
### draw the inner rectangle
##innerRect = Rectangle(inlowDiag, inhighDiag)
##innerRect.draw(win)
##
### BOTTOM
### Go Square
##golowDiag = Point(182, 182)
##gohighDiag = Point(200, 200)
##goRect = Rectangle(golowDiag, gohighDiag)
##goRect.draw(win)
##goLabel = Text(Point(191,191), 'GO')
##goLabel.setTextColor('maroon')
##goLabel.setStyle('bold')
##goLabel.setSize(10)
##goLabel.draw(win)
##
### Mediterranean Ave (Purple)
##MedilowDiag = Point(164, 182)
##MedihighDiag = Point(182, 200)
##MediRect = Rectangle(MedilowDiag, MedihighDiag)
##MediRect.draw(win)
##MediLabel = Text(Point(173, 191), '1')
##MediLabel.setTextColor('purple')
##MediLabel.setStyle('bold')
##MediLabel.setSize(10)
##MediLabel.draw(win)
### if this is drawn 
### print('Mediterranean Ave')
##
### Community Chest
##CC1lowDiag = Point(146, 182)
##CC1highDiag = Point(164, 200)
##CC1Rect = Rectangle(CC1lowDiag, CC1highDiag)
##CC1Rect.draw(win)
##CC1Label = Text(Point(155, 191), 'CC')
##CC1Label.setTextColor('dodgerblue')
##CC1Label.setStyle('bold')
##CC1Label.setSize(10)
##CC1Label.draw(win)
### if this is drawn
### print('Community Chest')
##
### Baltic Ave (Purple)
##BallowDiag = Point(128, 182)
##BalhighDiag = Point(146, 200)
##BalRect = Rectangle(BallowDiag, BalhighDiag)
##BalRect.draw(win)
##BalLabel = Text(Point(137, 191), '2')
##BalLabel.setTextColor('purple')
##BalLabel.setStyle('bold')
##BalLabel.setSize(10)
##BalLabel.draw(win)
##
### Income Tax
##TaxlowDiag = Point(110, 182)
##TaxhighDiag = Point(128, 200)
##TaxRect = Rectangle(TaxlowDiag, TaxhighDiag)
##TaxRect.draw(win)
##TaxLabel = Text(Point(119, 191), 'T')
##TaxLabel.setTextColor('gray')
##TaxLabel.setStyle('bold')
##TaxLabel.setSize(10)
##TaxLabel.draw(win)
##
### Reading Railroad (Black)
##RRlowDiag = Point(92, 182)
##RRhighDiag = Point(110, 200)
##RRRect = Rectangle(RRlowDiag, RRhighDiag)
##RRRect.draw(win)
##RRLabel = Text(Point(101, 191), 'RR')
##RRLabel.setTextColor('black')
##RRLabel.setStyle('bold')
##RRLabel.setSize(10)
##RRLabel.draw(win)
##
### Oriental Ave (Light Blue)
##OrilowDiag = Point(74, 182)
##OrihighDiag = Point(92, 200)
##OriRect = Rectangle(OrilowDiag, OrihighDiag)
##OriRect.draw(win)
##OriLabel = Text(Point(83, 191), '3')
##OriLabel.setTextColor('blue')
##OriLabel.setStyle('bold')
##OriLabel.setSize(10)
##OriLabel.draw(win)
##
### Chance
##C1lowDiag = Point(56, 182)
##C1highDiag = Point(74, 200)
##C1Rect = Rectangle(C1lowDiag, C1highDiag)
##C1Rect.draw(win)
##C1Label = Text(Point(65, 191), '?')
##C1Label.setTextColor('magenta')
##C1Label.setStyle('bold')
##C1Label.setSize(10)
##C1Label.draw(win)
##
### Vermont Ave (Light Blue)
##VerlowDiag = Point(38, 182)
##VerhighDiag = Point(56, 200)
##VerRect = Rectangle(VerlowDiag, VerhighDiag)
##VerRect.draw(win)
##VerLabel = Text(Point(47, 191), '4')
##VerLabel.setTextColor('blue')
##VerLabel.setStyle('bold')
##VerLabel.setSize(10)
##VerLabel.draw(win)
##
### Connecticut Ave (Light Blue)
##ConlowDiag = Point(18, 182)
##ConhighDiag = Point(38, 200)
##ConRect = Rectangle(ConlowDiag, ConhighDiag)
##ConRect.draw(win)
##ConLabel = Text(Point(29, 191), '5')
##ConLabel.setTextColor('blue')
##ConLabel.setStyle('bold')
##ConLabel.setSize(10)
##ConLabel.draw(win)
##
### Jail
##JaillowDiag = Point(0, 182)
##JailhighDiag = Point(18, 200)
##JailRect = Rectangle(JaillowDiag, JailhighDiag)
##JailRect.draw(win)
##JailLabel = Text(Point(9, 191), 'J')
##JailLabel.setTextColor('silver')
##JailLabel.setStyle('bold')
##JailLabel.setSize(10)
##JailLabel.draw(win)
##
### LEFT SIDE
### St. Charles Place (Pink)
##SClowDiag = Point(0, 164)
##SChighDiag = Point(18, 182)
##SCRect = Rectangle(SClowDiag, SChighDiag)
##SCRect.draw(win)
##SCLabel = Text(Point(9, 173), '6')
##SCLabel.setTextColor('pink')
##SCLabel.setStyle('bold')
##SCLabel.setSize(10)
##SCLabel.draw(win)
##
### Electric Company
##EllowDiag = Point(0, 146)
##ElhighDiag = Point(18, 164)
##ElRect = Rectangle(EllowDiag, ElhighDiag)
##ElRect.draw(win)
##ElLabel = Text(Point(9, 155), 'EC')
##ElLabel.setTextColor('white')
##ElLabel.setStyle('bold')
##ElLabel.setSize(10)
##ElLabel.draw(win)
##
### States Ave (Pink)
##StlowDiag = Point(0, 128)
##SthighDiag = Point(18, 146)
##StRect = Rectangle(StlowDiag, SthighDiag)
##StRect.draw(win)
##StLabel = Text(Point(9, 137), '7')
##StLabel.setTextColor('pink')
##StLabel.setStyle('bold')
##StLabel.setSize(10)
##StLabel.draw(win)
##
### Virginia Ave (Pink)
##VAlowDiag = Point(0, 110)
##VAhighDiag = Point(18, 128)
##VARect = Rectangle(VAlowDiag, VAhighDiag)
##VARect.draw(win)
##VALabel = Text(Point(9, 119), '8')
##VALabel.setTextColor('pink')
##VALabel.setStyle('bold')
##VALabel.setSize(10)
##VALabel.draw(win)
##
### Pennsylvania Railroad (Black)
##PRlowDiag = Point(0, 92)
##PRhighDiag = Point(18, 110)
##PRRect = Rectangle(PRlowDiag, PRhighDiag)
##PRRect.draw(win)
##PRLabel = Text(Point(9, 101), 'PR')
##PRLabel.setTextColor('black')
##PRLabel.setStyle('bold')
##PRLabel.setSize(10)
##PRLabel.draw(win)
##
### St. James Place (Orange)
##SJlowDiag = Point(0, 74)
##SJhighDiag = Point(18, 92)
##SJRect = Rectangle(SJlowDiag, SJhighDiag)
##SJRect.draw(win)
##SJLabel = Text(Point(9, 83), '9')
##SJLabel.setTextColor('orange')
##SJLabel.setStyle('bold')
##SJLabel.setSize(10)
##SJLabel.draw(win)
##
### Community Chest
##CC2lowDiag = Point(0, 56)
##CC2highDiag = Point(18, 74)
##CC2Rect = Rectangle(CC2lowDiag, CC2highDiag)
##CC2Rect.draw(win)
##CC2Label = Text(Point(9, 65), 'CC')
##CC2Label.setTextColor('dodgerblue')
##CC2Label.setStyle('bold')
##CC2Label.setSize(10)
##CC2Label.draw(win)
##
### Tennessee Ave (Orange)
##TenlowDiag = Point(0, 38)
##TenhighDiag = Point(18, 56)
##TenRect = Rectangle(TenlowDiag, TenhighDiag)
##TenRect.draw(win)
##TenLabel = Text(Point(9, 47), '10')
##TenLabel.setTextColor('orange')
##TenLabel.setStyle('bold')
##TenLabel.setSize(10)
##TenLabel.draw(win)
##
### New York Ave (Orange)
##NYlowDiag = Point(0, 18)
##NYhighDiag = Point(18, 38)
##NYRect = Rectangle(NYlowDiag, NYhighDiag)
##NYRect.draw(win)
##NYLabel = Text(Point(9, 28), '11')
##NYLabel.setTextColor('orange')
##NYLabel.setStyle('bold')
##NYLabel.setSize(10)
##NYLabel.draw(win)
##
### Free Parking
##FPlowDiag = Point(0, 0)
##FPhighDiag = Point(18, 18)
##FPRect = Rectangle(FPlowDiag, FPhighDiag)
##FPRect.draw(win)
##FPLabel = Text(Point(9, 9), 'FP')
##FPLabel.setTextColor('springgreen')
##FPLabel.setStyle('bold')
##FPLabel.setSize(10)
##FPLabel.draw(win)
##
### TOP
### Kentucky Ave (Red)
##KAlowDiag = Point(18, 18)
##KAhighDiag = Point(38, 0)
##KARect = Rectangle(KAlowDiag, KAhighDiag)
##KARect.draw(win)
##KALabel = Text(Point(28, 9), '12')
##KALabel.setTextColor('red')
##KALabel.setStyle('bold')
##KALabel.setSize(10)
##KALabel.draw(win)
##
### Chance
##C2lowDiag = Point(38, 18)
##C2highDiag = Point(56, 0)
##C2Rect = Rectangle(C2lowDiag, C2highDiag)
##C2Rect.draw(win)
##C2Label = Text(Point(47, 9), '?')
##C2Label.setTextColor('magenta')
##C2Label.setStyle('bold')
##C2Label.setSize(10)
##C2Label.draw(win)
##
### Indiana Ave (Red)
##IndlowDiag = Point(56, 18)
##IndhighDiag = Point(74, 0)
##IndRect = Rectangle(IndlowDiag, IndhighDiag)
##IndRect.draw(win)
##IndLabel = Text(Point(65, 9), '13')
##IndLabel.setTextColor('red')
##IndLabel.setStyle('bold')
##IndLabel.setSize(10)
##IndLabel.draw(win)
##
### Illinois Ave (Red)
##IlllowDiag = Point(74, 18)
##IllhighDiag = Point(92, 0)
##IllRect = Rectangle(IlllowDiag, IllhighDiag)
##IllRect.draw(win)
##IllLabel = Text(Point(83, 9), '14')
##IllLabel.setTextColor('red')
##IllLabel.setStyle('bold')
##IllLabel.setSize(10)
##IllLabel.draw(win)
##
### B&O Railroad
##BOlowDiag = Point(92, 18)
##BOhighDiag = Point(110, 0)
##BORect = Rectangle(BOlowDiag, BOhighDiag)
##BORect.draw(win)
##BOLabel = Text(Point(101, 9), 'BO')
##BOLabel.setTextColor('black')
##BOLabel.setStyle('bold')
##BOLabel.setSize(10)
##BOLabel.draw(win)
##
### Atlantic Ave (Yellow)
##AtllowDiag = Point(110, 18)
##AtlhighDiag = Point(128, 0)
##AtlRect = Rectangle(AtllowDiag, AtlhighDiag)
##AtlRect.draw(win)
##AtlLabel = Text(Point(119, 9), '15')
##AtlLabel.setTextColor('yellow')
##AtlLabel.setStyle('bold')
##AtlLabel.setSize(10)
##AtlLabel.draw(win)
##
### Ventnor Ave (Yellow)
##VenlowDiag = Point(128, 18)
##VenhighDiag = Point(146, 0)
##VenRect = Rectangle(VenlowDiag, VenhighDiag)
##VenRect.draw(win)
##VenLabel = Text(Point(137, 9), '16')
##VenLabel.setTextColor('yellow')
##VenLabel.setStyle('bold')
##VenLabel.setSize(10)
##VenLabel.draw(win)
##
### Water Works
##WWlowDiag = Point(146, 18)
##WWhighDiag = Point(164, 0)
##WWRect = Rectangle(WWlowDiag, WWhighDiag)
##WWRect.draw(win)
##WWLabel = Text(Point(155, 9), 'WW')
##WWLabel.setTextColor('white')
##WWLabel.setStyle('bold')
##WWLabel.setSize(10)
##WWLabel.draw(win)
##
### Marvin Gardens (Yellow)
##MGlowDiag = Point(164, 18)
##MGhighDiag = Point(182, 0)
##MGRect = Rectangle(MGlowDiag, MGhighDiag)
##MGRect.draw(win)
##MGLabel = Text(Point(173, 9), '17')
##MGLabel.setTextColor('yellow')
##MGLabel.setStyle('bold')
##MGLabel.setSize(10)
##MGLabel.draw(win)
##
### Go To Jail
##G2JlowDiag = Point(182, 18)
##G2JhighDiag = Point(200, 0)
##G2JRect = Rectangle(G2JlowDiag, G2JhighDiag)
##G2JRect.draw(win)
##G2JLabel = Text(Point(191, 9), '>J')
##G2JLabel.setTextColor('silver')
##G2JLabel.setStyle('bold')
##G2JLabel.setSize(10)
##G2JLabel.draw(win)
##
### RIGHT
### Pacific Ave (Green)
##PaclowDiag = Point(200, 38)
##PachighDiag = Point(182, 18)
##PacRect = Rectangle(PaclowDiag, PachighDiag)
##PacRect.draw(win)
##PacLabel = Text(Point(191, 28), '18')
##PacLabel.setTextColor('green')
##PacLabel.setStyle('bold')
##PacLabel.setSize(10)
##PacLabel.draw(win)
##
### North Carolina Ave (Green)
##NClowDiag = Point(200, 56)
##NChighDiag = Point(182, 38)
##NCRect = Rectangle(NClowDiag, NChighDiag)
##NCRect.draw(win)
##NCLabel = Text(Point(191, 47), '19')
##NCLabel.setTextColor('green')
##NCLabel.setStyle('bold')
##NCLabel.setSize(10)
##NCLabel.draw(win)
##
### Community Chest
##CC3lowDiag = Point(200, 74)
##CC3highDiag = Point(182, 56)
##CC3Rect = Rectangle(CC3lowDiag, CC3highDiag)
##CC3Rect.draw(win)
##CC3Label = Text(Point(191, 65), 'CC')
##CC3Label.setTextColor('dodgerblue')
##CC3Label.setStyle('bold')
##CC3Label.setSize(10)
##CC3Label.draw(win)
##
### Pennsylvania Ave (Green)
##PAlowDiag = Point(200, 92)
##PAhighDiag = Point(182, 74)
##PARect = Rectangle(PAlowDiag, PAhighDiag)
##PARect.draw(win)
##PALabel = Text(Point(191, 83), '20')
##PALabel.setTextColor('green')
##PALabel.setStyle('bold')
##PALabel.setSize(10)
##PALabel.draw(win)
##
### Short Line
##SLlowDiag = Point(200, 110)
##SLhighDiag = Point(182, 92)
##SLRect = Rectangle(SLlowDiag, SLhighDiag)
##SLRect.draw(win)
##SLLabel = Text(Point(191, 101), 'SL')
##SLLabel.setTextColor('black')
##SLLabel.setStyle('bold')
##SLLabel.setSize(10)
##SLLabel.draw(win)
##
### Chance
##C3lowDiag = Point(200, 128)
##C3highDiag = Point(182, 110)
##C3Rect = Rectangle(C3lowDiag, C3highDiag)
##C3Rect.draw(win)
##C3Label = Text(Point(191, 119), '?')
##C3Label.setTextColor('magenta')
##C3Label.setStyle('bold')
##C3Label.setSize(10)
##C3Label.draw(win)
##
### Park Place
##PPlowDiag = Point(200, 146)
##PPhighDiag = Point(182, 128)
##PPRect = Rectangle(PPlowDiag, PPhighDiag)
##PPRect.draw(win)
##PPLabel = Text(Point(191, 137), '21')
##PPLabel.setTextColor('navy')
##PPLabel.setStyle('bold')
##PPLabel.setSize(10)
##PPLabel.draw(win)
##
### Luxury Tax
##LTlowDiag = Point(200, 164)
##LThighDiag = Point(182, 146)
##LTRect = Rectangle(LTlowDiag, LThighDiag)
##LTRect.draw(win)
##LTLabel = Text(Point(191, 155), 'T')
##LTLabel.setTextColor('gray')
##LTLabel.setStyle('bold')
##LTLabel.setSize(10)
##LTLabel.draw(win)
##
### Boardwalk
##BlowDiag = Point(200, 182)
##BhighDiag = Point(182, 164)
##BRect = Rectangle(BallowDiag, BalhighDiag)
##BRect.draw(win)
##BLabel = Text(Point(191, 173), '22')
##BLabel.setTextColor('navy')
##BLabel.setStyle('bold')
##BLabel.setSize(10)
##BLabel.draw(win)
